spring:
  config:
    import: optional:env.properties    # 환경변수 파일 import
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  
  security:
    user:
      name: user
      password: user123

mybatis:
  type-aliases-package: com.wor.dash.*.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.mybatis: DEBUG
    com.wor.dash: DEBUG

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.wor.dash

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_VALIDITY}
  refresh-token-expiration: ${JWT_REFRESH_VALIDITY}

project:
  origin-url: http://localhost:5173